import { GetStaticProps } from "next";
import Head from 'next/head'
import fetchMediumPosts from "../lib/medium/client";
import { PostProps } from "../app/mediumSlice";

interface PageProps {
  mediumPosts: PostProps[];
}

export default function Home(props: PageProps) {
  const { mediumPosts } = props;


  return (
    <>
      <Head>
        <title>Interview Template</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='bg-gray-200 h-full w-full flex justify-center'>
        <div className='w-full max-w-7xl bg-gray-300 px-5 py-20 md:px-10'>
          <h1 className='text-3xl font-bold mb-4'>Interview Template</h1>
          <p>This interview template is designed to test your skills on the following frontend technologies:</p>
          <ul className='list-disc pl-4 mt-4'>
            <li>React.js</li>
            <li>Next.js</li>
            <li>Typescript</li>
            <li>Tailwind CSS</li>
          </ul>
        </div>
      </div>
    </>
  )
}

export const getStaticProps: GetStaticProps = async () => {
  const mediumPosts = await fetchMediumPosts();

  return {
    props: {
      mediumPosts,
    },
  };
};
